export default Object.freeze({
    INITIALIZE:             'INITIALIZE',
    START_FETCHING_AUTH:    'START_FETCHING_AUTH',
    STOP_FETCHING_AUTH:     'STOP_FETCHING_AUTH',
    START_FETCHING_FEED:    'START_FETCHING_FEED',
    STOP_FETCHING_FEED:     'STOP_FETCHING_FEED',
    START_FETCHING_PROFILE: 'START_FETCHING_PROFILE',
    STOP_FETCHING_PROFILE:  'STOP_FETCHING_PROFILE',
    START_EDITING_PROFILE:  'START_EDITING_PROFILE',
    STOP_EDITING_PROFILE:   'STOP_EDITING_PROFILE',
    START_FETCHING_AVATAR:  'START_FETCHING_AVATAR',
    STOP_FETCHING_AVATAR:   'STOP_FETCHING_AVATAR',
    START_EDITING_PASSWORD: 'START_EDITING_PASSWORD',
    STOP_EDITING_PASSWORD:  'STOP_EDITING_PASSWORD'
});
